### ISSUE TITLE
Tried to use on Debian- get error

### ISSUE THREAD

**Issue by EICUTDEV1** [orkunza/STM32_Timer_Calculator_GUI#1]
Hi,
When I used python to run it I got
STM32_Timer_Calculator_GUI/timerCalc.py", line 191, in <module>
    root.iconbitmap(iconfile.name)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "/tmp/tmp879l_r9n" not defined

Please provide .appimage if you can. 
Regards

**Comment by yevhenboichuk** [comment]
`~/STM32_Timer_Calculator_GUI - (master) > python timerCalc.py            
Traceback (most recent call last):
  File "/home/yevhenb/STM32_Timer_Calculator_GUI/timerCalc.py", line 191, in <module>
    root.iconbitmap(iconfile.name)
  File "/usr/lib/python3.12/tkinter/__init__.py", line 2155, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "/tmp/tmpbh2f74h6" not defined
(venv) yevhenb:~/STM32_Timer_Calculator_GUI - (master) > python timerCalc.py
Traceback (most recent call last):
  File "/home/yevhenb/STM32_Timer_Calculator_GUI/timerCalc.py", line 191, in <module>
    root.iconbitmap(iconfile.name)
  File "/usr/lib/python3.12/tkinter/__init__.py", line 2155, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "/tmp/tmpkh_lsouw" not defined
`

Ubuntu 24.04 same
